on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: appmusicacr.azurecr.io
        username: ${{ secrets.acr_appmusicacr_username }}
        password: ${{ secrets.acr_appmusicacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t appmusicacr.azurecr.io/musicapp:${{ github.sha }}
        docker push appmusicacr.azurecr.io/musicapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_musicapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep musicapp225a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace musicapp225a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: musicapp225a
        container-registry-url: appmusicacr.azurecr.io
        container-registry-username: ${{ secrets.acr_appmusicacr_username }}
        container-registry-password: ${{ secrets.acr_appmusicacr_password }}
        secret-name: musicappdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: musicapp225a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          appmusicacr.azurecr.io/musicapp:${{ github.sha }}
        imagepullsecrets: |
          musicappdockerauth